INSERT INTO preferences
(user_id, number_of_kids_preferred, gender_preferred)
VALUES
(${user_id},
${number_of_kids_preferred},
${gender_preferred})

returning user_id, number_of_kids_preferred, gender_preferred;

-- changed ID to user_id.  This is what I think you are wanting, maybe, id is auto-generated by the table to be the row (serial primary key).  Line 8 might not need to change.  I need to check what you are using these valuess for.